#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: debian
#+date: <2022-04-11 Mon>
#+author: Andrew M Davis, PhD
#+email: @reconmaster:matrix.org
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.2 (Org mode 9.4.6)
#+cite_export:
* Introduction
For beginners, I'd recommend a [[https://en.wikipedia.org/wiki/Debian][debian]]-based distro for simplicity.
* Distros
** [[https://www.debian.org/][Debian]]
** [[https://linuxmint.com/][Linux Mint]]
*** [[https://linuxmint.com/download.php][download]]
Select the bit and desktop version you'd like to run.

As a physicist, I'd recommend the lightweight [[https://en.wikipedia.org/wiki/Xfce][Xfce]] to save on
electricity. Older computers may only have a [[https://en.wikipedia.org/wiki/Central_processing_unit][CPU]] that supports 32-bit,
and can still function beautifully as a mind mirror. People routinely
underestimate the power of a pen.

Create a [[id:fa794bbd-876d-4889-a7be-b0962db9110a][bootable usb]] and install to disk if you like what you see.
* Software
** admin
#+BEGIN_SRC sh
sudo apt-get install\
        etckeeper\
        glances\
        htop\
        iftop\
        logwatch\
        most\
        ngrep\
        parallel\
        pydf\
        python-pip\
        ranger\
        ruby\
        w3m\
        xclip
#+END_SRC
** aesthetics
*** fonts
#+BEGIN_SRC sh
sudo apt-get install\
        fonts-hack-otf\
        fonts-inconsolata\
        fonts-noto\
        fonts-noto-cjk\
        fonts-roboto
#+END_SRC
** archive
#+BEGIN_SRC sh
sudo apt-get install\
        file-roller\
        p7zip
#+END_SRC
** cli
#+BEGIN_SRC sh
sudo apt-get install\
        tmux\
        zsh
#+END_SRC
** cloud
#+BEGIN_SRC sh
sudo apt-get install\
        syncthing
#+END_SRC
** emacs
#+BEGIN_SRC sh
sudo apt-get install\
     emacs25\
     pandoc\
     xpdf
#+END_SRC
**** email
#+BEGIN_SRC sh
sudo apt-get install autoconf-archive isync msmtp mu4e
#+END_SRC
**** hunspell
#+BEGIN_SRC sh
sudo apt-get install hunspell-en-us
#+END_SRC
** language
#+BEGIN_SRC sh
sudo apt-get install tagainijisho
#+END_SRC
** media
**** books
#+BEGIN_SRC sh
sudo apt-get install calibre
#+END_SRC
**** collections
#+BEGIN_SRC sh
sudo apt-get install tellico
#+END_SRC
**** images
#+BEGIN_SRC sh
sudo apt-get install digikam feh gimp inkscape
#+END_SRC
**** music
#+BEGIN_SRC sh
sudo apt-get install beets\
       flac\
       mopidy\
       mopidy-beets\
       mopidy-podcast\
       mopidy-soundcloud\
       mp3val\
       ncmpcpp\
       python-mpd\
       python-pylast\
       python-requests\
       sox
#+END_SRC
**** video
#+BEGIN_SRC sh
sudo apt-get install\
     blender\
     kodi\
     vlc
#+END_SRC
** office
#+BEGIN_SRC sh
sudo apt-get install\
     libreoffice\
     okular\
     scribus
#+END_SRC
** programming
**** git
#+BEGIN_SRC sh
sudo apt-get install git git-annex
#+END_SRC
**** latex
#+BEGIN_SRC sh
sudo apt-get install texlive-latex-recommended texlive-lang-japanese
#+END_SRC
**** python
#+BEGIN_SRC sh
sudo apt-get install\
       flake8\
       python\
       python-ipdb\
       python-jedi\
       python-pip
       python-pyqt5\
       jupyter
#+END_SRC
** research
#+BEGIN_SRC sh
sudo apt-get install\
       python-numpy\
       python-scipy \
       python-matplotlib\
       python-pandas
#+END_SRC
** security
#+BEGIN_SRC sh
sudo apt-get install\
     pass\
     tor
#+END_SRC

* TODO Methods
Here are some useful commands for maintaining the installation.
** update
Keep the things minty fresh.
    #+begin_src sh
sudo apt-get update

sudo apt-get upgrade
    #+end_src
